name: elevate
description: Elevate is an upcoming secure chat app that does not store any user data for longer than 24 hours.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase Packages
  firebase_core: ^2.15.0
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1

  # Encrypting the messages with AES
  encrypt: ^5.0.1

  # URL Launcher
  url_launcher: ^6.1.14

  # Sliables ~ used for deleteing the messages
  flutter_slidable: ^3.0.0

  # Lottie ~ used for animations throughout the app
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/