name: elevate
description: Elevate is a secure chat app that does not store any user data for longer than 24 hours.
version: 1.1.0

publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Packages
  firebase_core: ^2.15.0
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  firebase_analytics: ^10.4.5
  firebase_messaging: ^14.6.7
  cloud_firestore: ^4.9.1

  # Encrypting the messages with AES
  encrypt: ^5.0.1

  # Image ~ used to resize & compress avatars
  image: ^4.0.17

  # Image picker ~ used to change the avatar
  image_picker: ^1.0.4

  # Sliables ~ used for deleteing the messages
  flutter_slidable: ^3.0.0

  # Lottie ~ used for animations throughout the app
  lottie: ^2.6.0

  # HTTP ~ used to send FCM Requests for Notifications
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/